version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: uvicorn core.app:create_app --host 0.0.0.0 --port 8080 --factory --reload
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./backend/src:/code/
    ports:
      - "8080:8080"
    networks:
      anime_lib:
        aliases:
          - anime_lib-backend
  
  migrations:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: alembic upgrade head
    env_file: .env
    volumes:
      - ./backend/src:/code/
    depends_on:
      - postgres
    networks:
      anime_lib:
        aliases:
          - anime_lib-migrations

  postgres:
    image: postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      anime_lib:
        aliases:
          - anime_lib-postgres

networks:
  anime_lib:
    external: true

volumes:
  postgres_data:
