"""add anime table

Revision ID: 485fbd674447
Revises: 63f50f7c2cd8
Create Date: 2023-05-28 16:20:35.658024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485fbd674447'
down_revision = '63f50f7c2cd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('type_', sa.String(length=32), nullable=True),
    sa.Column('publishing_year', sa.Integer(), nullable=True),
    sa.Column('poster_link', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anime')
    # ### end Alembic commands ###
